import enum
from typing import List


class HandLandmark(enum.IntEnum):
    """The 21 hand landmarks."""
    WRIST = 0
    THUMB_CMC = 1
    THUMB_MCP = 2
    THUMB_IP = 3
    THUMB_TIP = 4
    INDEX_FINGER_MCP = 5
    INDEX_FINGER_PIP = 6
    INDEX_FINGER_DIP = 7
    INDEX_FINGER_TIP = 8
    MIDDLE_FINGER_MCP = 9
    MIDDLE_FINGER_PIP = 10
    MIDDLE_FINGER_DIP = 11
    MIDDLE_FINGER_TIP = 12
    RING_FINGER_MCP = 13
    RING_FINGER_PIP = 14
    RING_FINGER_DIP = 15
    RING_FINGER_TIP = 16
    PINKY_MCP = 17
    PINKY_PIP = 18
    PINKY_DIP = 19
    PINKY_TIP = 20


HAND_PALM_CONNECTIONS = ((0, 1), (0, 5), (9, 13), (13, 17), (5, 9), (0, 17))

HAND_THUMB_CONNECTIONS = ((1, 2), (2, 3), (3, 4))

HAND_INDEX_FINGER_CONNECTIONS = ((5, 6), (6, 7), (7, 8))

HAND_MIDDLE_FINGER_CONNECTIONS = ((9, 10), (10, 11), (11, 12))

HAND_RING_FINGER_CONNECTIONS = ((13, 14), (14, 15), (15, 16))

HAND_PINKY_FINGER_CONNECTIONS = ((17, 18), (18, 19), (19, 20))

HAND_CONNECTIONS = frozenset().union(*[
    HAND_PALM_CONNECTIONS, HAND_THUMB_CONNECTIONS,
    HAND_INDEX_FINGER_CONNECTIONS, HAND_MIDDLE_FINGER_CONNECTIONS,
    HAND_RING_FINGER_CONNECTIONS, HAND_PINKY_FINGER_CONNECTIONS
])

HL = HandLandmark
HAND_LANDMARK_ANGLES: List[List[HandLandmark]] = [
    [HL.THUMB_CMC, HL.THUMB_MCP, HL.THUMB_IP],
    [HL.THUMB_MCP, HL.THUMB_IP, HL.THUMB_TIP],
    [HL.INDEX_FINGER_MCP, HL.INDEX_FINGER_PIP, HL.INDEX_FINGER_DIP],
    [HL.INDEX_FINGER_PIP, HL.INDEX_FINGER_DIP, HL.INDEX_FINGER_TIP],
    [HL.MIDDLE_FINGER_MCP, HL.MIDDLE_FINGER_PIP, HL.MIDDLE_FINGER_DIP],
    [HL.MIDDLE_FINGER_PIP, HL.MIDDLE_FINGER_DIP, HL.MIDDLE_FINGER_TIP],
    [HL.RING_FINGER_MCP, HL.RING_FINGER_PIP, HL.RING_FINGER_DIP],
    [HL.RING_FINGER_PIP, HL.RING_FINGER_DIP, HL.RING_FINGER_TIP],
    [HL.PINKY_MCP, HL.PINKY_PIP, HL.PINKY_DIP],
    [HL.PINKY_PIP, HL.PINKY_DIP, HL.PINKY_TIP],
    [HL.THUMB_IP, HL.WRIST, HL.INDEX_FINGER_MCP],
    [HL.THUMB_IP, HL.WRIST, HL.PINKY_MCP],
    [HL.WRIST, HL.INDEX_FINGER_MCP, HL.INDEX_FINGER_PIP],
    [HL.WRIST, HL.MIDDLE_FINGER_MCP, HL.MIDDLE_FINGER_PIP],
    [HL.WRIST, HL.RING_FINGER_MCP, HL.RING_FINGER_PIP],
    [HL.WRIST, HL.PINKY_MCP, HL.PINKY_PIP],
    [HL.WRIST, HL.THUMB_MCP, HL.THUMB_IP],
]

HAND_LANDMARK_DISTANCES: List[List[HandLandmark]] = [
    [HL.THUMB_TIP, HL.INDEX_FINGER_TIP],
    [HL.THUMB_TIP, HL.MIDDLE_FINGER_TIP],
    [HL.THUMB_TIP, HL.RING_FINGER_TIP],
    [HL.THUMB_TIP, HL.PINKY_TIP],
    [HL.THUMB_TIP, HL.INDEX_FINGER_DIP],
    [HL.THUMB_TIP, HL.MIDDLE_FINGER_DIP],
    [HL.THUMB_TIP, HL.RING_FINGER_DIP],
    [HL.THUMB_TIP, HL.PINKY_DIP],
    [HL.THUMB_TIP, HL.INDEX_FINGER_PIP],
    [HL.THUMB_TIP, HL.MIDDLE_FINGER_PIP],
    [HL.THUMB_TIP, HL.RING_FINGER_PIP],
    [HL.THUMB_TIP, HL.PINKY_PIP],
    [HL.THUMB_TIP, HL.INDEX_FINGER_MCP],
    [HL.THUMB_TIP, HL.MIDDLE_FINGER_MCP],
    [HL.THUMB_TIP, HL.RING_FINGER_MCP],
    [HL.THUMB_TIP, HL.PINKY_MCP],
    [HL.WRIST, HL.THUMB_TIP],
    [HL.WRIST, HL.INDEX_FINGER_TIP],
    [HL.WRIST, HL.MIDDLE_FINGER_TIP],
    [HL.WRIST, HL.RING_FINGER_TIP],
    [HL.WRIST, HL.PINKY_TIP],
    [HL.THUMB_CMC, HL.INDEX_FINGER_TIP],
    [HL.THUMB_CMC, HL.MIDDLE_FINGER_TIP],
    [HL.THUMB_CMC, HL.RING_FINGER_TIP],
    [HL.THUMB_CMC, HL.PINKY_TIP],
    [HL.INDEX_FINGER_TIP, HL.INDEX_FINGER_MCP],
    [HL.MIDDLE_FINGER_TIP, HL.MIDDLE_FINGER_MCP],
    [HL.RING_FINGER_TIP, HL.RING_FINGER_MCP],
    [HL.PINKY_TIP, HL.PINKY_MCP],
]


class HandEvent(enum.IntEnum):
    """Hand Events."""
    MOUSE_MOVE = 0
    MOUSE_CLICK = 1
    MOUSE_DRAG = 2
    MOUSE_RIGHT_CLICK = 3
    AUDIO_INPUT = 4
    MOUSE_SCROLL = 5
    VOLUME_UP = 6
    VOLUME_DOWN = 7
    COPY_TEXT = 8
    PASTE_TEXT = 9
    MOUSE_NO_EVENT = 10


class GUIEvents(enum.IntEnum):
    """GUI Events."""
    TRACKING_SMOOTHNESS = 0
    MOUSE_SMOOTHNESS = 1
    SHOW_WEBCAM = 2
    MOUSE_POINTER = 3
    EXIT = 4
